branches:
  only:
  - master
  - develop
language: python
python:
  - "3.5"
# Install C libraries
addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
# Command to install dependencies
install: python setup.py install
# Command to run tests
script: nosetests
